name: Build and Release

on:
  push:
    branches: [main]

jobs:

  build:
    name: Build executable
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: Build executable
      run: pyinstaller --onefile --uac-admin dns-changer.py
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/dns-changer.exe
        
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: executable
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dns-changer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}