name: Build and Release

on:
  push:
    branches: [main]

jobs:

  build:
    name: Build executable
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: Build executable
      run: pyinstaller --onefile --uac-admin dns-changer.py
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/dns-changer.exe
        
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: executable

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dns-changer.exe"
        generateReleaseNotes: true
# - name: Create Release
#   uses: ncipollo/release-action@v1
#   with:
#     artifacts: "yourscript.exe"
#     generateReleaseNotes: true