name: Build Python Script to EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build EXE
      run: |
        pyinstaller --onefile --uac-admin dns-changer.py
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dns-changer
        path: dist/dns-changer.exe